[tool.poetry]
name = "berri_ai"
version = "0.15.1"
description = ""
authors = ["Team Berri <clerkieai@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"
pipreqs = "^0.4.11"
requests = "^2.28.2"
gpt-index = "^0.3.6"
html2text = "^2020.1.16"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
