[tool.poetry]
name = "cgePy"
version = "0.5.10"
description = "Tools for developing graphical programs inside the console."
authors = ["catbox305 <lion712yt@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

