
[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "site_requests"
version = "0.0.4"

dependencies =  [
    "bs4 == 0.0.1",
    "requests >= 2.28.2",
]

authors = [
    { name="your name", email="you_mail@example.com" },
]
description = "A small site requests package"
readme = "README.md"
#license = {file = "LICENSE"}
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    #"License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    #"Private :: Do Not Upload",
]

[project.urls]
"Homepage" = "https://github.com/your-name/site-requests"
"Bug Tracker" = "https://github.com/your-name/site-requests/issues"

