[tool.poetry]
name = "pcluster-cli"
version = "0.1.2"
description = "CLI for easy AWS parallel cluster management"
authors = ["rsingh <rsingh@altoslabs.com>"]
readme = "README.md"
packages = [{include = "pcluster_cli"}]

[tool.poetry.scripts]
pcl = "pcluster_cli.main:main"

[tool.poetry.dependencies]
python = "^3.10"
aws-parallelcluster = "^3.4.1"
tabulate = "0.8.10"
sentry-sdk = "^1.14.0"
jinja2 = "^3.1.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
