[build-system]
requires = [ "poetry-core",]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "pipable"
version = "0.2.0"
description = "pseudo pipe operation in python"
authors = [ "Kelvin Ng <hoishing@gmail.com>",]
readme = "README.md"
license = "MIT"
repository = "https://github.com/hoishing/pipable"
homepage = "https://hoishing.github.io/pipable"
keywords = [ "pipe", "FP", "functional programming", "chain",]

[tool.poetry.dependencies]
python = "^3.8"

[tool.poetry.scripts]
pump = "pump:main"

[tool.poetry.group.dev]
optional = true

[tool.poetry.group.dev.dependencies]
auto-changelog = "^0.6.0"
pytest = "^7.2.1"
coverage = "^7.1.0"
black = "^22.12.0"
mkdocs-material = "^9.0.9"
ipykernel = "^6.20.2"
toml = "^0.10.2"
click = "^8.1.3"

[tool.poetry.group.dev.dependencies.genbadge]
extras = [ "coverage",]
version = "^1.1.0"

[tool.poetry.group.dev.dependencies.mkdocstrings]
extras = [ "python",]
version = "^0.20.0"
