[project]
name = "b2-utils"
version = "0.1.9"
authors = [
  { name="Felipe Sena", email="felipesena@b2bit.company" },
]
description = "A useful package provided by B2BIT"
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
    "Django>=4.0.6",
    "django-model-utils>=4.3.1",
    "djangorestframework>=3.13.1",
    "model-bakery>=1.9.0",
    "Faker>=13.3.4",
    "Pillow>=9.4.0",
    "validate-docbr>=1.10.0"
]

[project.urls]
"Homepage" = "https://gitlab.com/b2bit.felipesena/b2-utils"

[tool.poetry]
name = "b2-utils"
version = "0.1.0"
description = ""
authors = ["Felipe Sena <felipesena.m@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.10"
wheel = "^0.38.4"
twine = "^4.0.2"
tqdm = "^4.64.1"
build = "^0.9.0"
validate-docbr = "^1.10.0"
Faker = "^15.3.4"
Django = "^4.1.5"
djangorestframework = "^3.14.0"
Pillow = "^9.4.0"
django-model-utils = "^4.3.1"
model-bakery = "^1.9.0"
pre-commit = "^3.0.0"
django-constance = "^2.9.1"
djangorestframework-simplejwt = "^5.2.2"

[tool.poetry.dev-dependencies]
black = "^22.3.0"
flake8 = "^4.0.1"
pylint = "^2.13.5"
pylint-django = "^2.5.3"
bandit = "^1.7.4"
ipython = "^8.2.0"

[tool.isort]
profile = 'black'

[tool.black]
preview = true

[tool.pylint.format]
max-line-length = "88"

[tool.pylint.master]
disable = ["C0114", "C0115", "C0116", "broad-except"]

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"
