[tool.poetry]
name = "optipack"
version = "0.0.10-dev"
description = "The optimal package for ML at OM"
authors = ["indigoYoshimaru"]
readme = "README.md"
include = ["optipack/.config/project_structure.yaml"]

[tool.poetry.dependencies]
python = "^3.9"
typer = "^0.7.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
optipack = "optipack.cli:run"

