[tool.poetry]
name = "ms_imputedhours_core"
version = "0.0.12"
description = "Core for several projects (Happeo, Alerts and Capacity)"
authors = ["Jonathan Rodriguez Alejos <jrodriguez.5716@gmail.com>"]
license = "GNU"
readme = "README.md"
homepage = "https://github.com/GoodCod3/ms-jirahours-core"
repository = "https://github.com/GoodCod3/ms-jirahours-core"
documentation = "https://github.com/GoodCod3/ms-jirahours-core"
keywords= ["ms", "imputedhours"]

[tool.poetry.dependencies]
python = ">3.7,<4"

[tool.poetry.dev-dependencies]
coverage = "*"
tox = "*"
codecov = "*"
flake8 = "*"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"