[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "ueqplusanalyze"
version = "0.0.2"
authors = [
    { name = "Jan Bernoth", email = "jan.bernoth@uni-potsdam.de" },
    { name = "Lewin KÃ¤stner", email = "lewin.kaestner@uni-potsdam.de" },
]
description = "Create statical analysis for UEQ+ data"
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

dependencies = [
    "pandas == 1.5.2",
    "numpy == 1.23.5",
    "matplotlib == 3.6.2",
    "jupyter == 1.0.0",
    "pytest == 7.2.1"]

[project.urls]
"Homepage" = "https://github.com/B3J4y/ueq-plus-data-analyze"
"Bug Tracker" = "https://github.com/B3J4y/ueq-plus-data-analyze/issues"
